//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example01.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebASPEntities1 : DbContext
    {
        public WebASPEntities1()
            : base("name=WebASPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand_2119110193> Brand_2119110193 { get; set; }
        public virtual DbSet<Category_2119110193> Category_2119110193 { get; set; }
        public virtual DbSet<Order_2119110193> Order_2119110193 { get; set; }
        public virtual DbSet<OrderDetail_2119110193> OrderDetail_2119110193 { get; set; }
        public virtual DbSet<Product_2119110193> Product_2119110193 { get; set; }
        public virtual DbSet<Users_2119110193> Users_2119110193 { get; set; }
    }
}
