//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example01.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail_2119110193
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int Productid { get; set; }
        public int Quantity { get; set; }
    }
}
